import PDFDocument from "pdfkit";
import { RISK_DESCRIPTIONS } from "../config/bhsConfig.js";

const COLORS = {
  green: "#16a34a",
  amber: "#d97706",
  red: "#dc2626",
  ink: "#0f172a",
  muted: "#64748b",
  line: "#e2e8f0",
};

const RISK_COLOR = {
  Low: COLORS.green,
  Moderate: COLORS.amber,
  High: "#ea580c",
  Critical: COLORS.red,
};

function fmtValue(kpi) {
  if (kpi.value === null || kpi.value === undefined) return "N/A";
  return kpi.unit === "percent" ? `${(kpi.value * 100).toFixed(1)}%` : kpi.value.toFixed(2);
}

/**
 * Stream a Business Health report PDF to `res`.
 * @param {object} record { periodLabel, businessName, createdAt, bhs, riskLevel,
 *   performanceBand, kpis[], recommendations[] }
 */
export function streamReport(res, record) {
  const doc = new PDFDocument({ size: "A4", margin: 50 });
  doc.pipe(res);

  // Header
  doc.fillColor(COLORS.ink).fontSize(22).text("RiskLens — Business Health Report", { align: "left" });
  doc.moveDown(0.2);
  doc.fillColor(COLORS.muted).fontSize(11).text(record.businessName || "");
  doc
    .fillColor(COLORS.muted)
    .fontSize(10)
    .text(`Period: ${record.periodLabel}    Generated: ${new Date(record.createdAt).toLocaleDateString()}`);
  doc.moveDown(0.6);
  doc.strokeColor(COLORS.line).moveTo(50, doc.y).lineTo(545, doc.y).stroke();
  doc.moveDown(0.8);

  // Score summary
  doc.fillColor(COLORS.ink).fontSize(14).text("Business Health Score");
  doc.moveDown(0.2);
  doc.fillColor(COLORS.ink).fontSize(40).text(`${record.bhs}`, { continued: true });
  doc.fillColor(COLORS.muted).fontSize(16).text("  / 100");
  doc.moveDown(0.2);
  doc.fillColor(RISK_COLOR[record.riskLevel] || COLORS.ink).fontSize(13)
    .text(`Risk Level: ${record.riskLevel}    Performance: ${record.performanceBand}`);
  doc.moveDown(0.3);
  doc.fillColor(COLORS.muted).fontSize(10).text(RISK_DESCRIPTIONS[record.riskLevel] || "");
  doc.moveDown(0.8);

  // KPI breakdown
  doc.fillColor(COLORS.ink).fontSize(14).text("KPI Breakdown");
  doc.moveDown(0.4);

  const startX = 50;
  let y = doc.y;
  doc.fontSize(10).fillColor(COLORS.muted);
  doc.text("Indicator", startX, y);
  doc.text("Value", startX + 230, y);
  doc.text("Score", startX + 330, y);
  doc.text("Status", startX + 420, y);
  y += 16;
  doc.strokeColor(COLORS.line).moveTo(startX, y).lineTo(545, y).stroke();
  y += 8;

  for (const kpi of record.kpis) {
    doc.fillColor(COLORS.ink).fontSize(11).text(kpi.label, startX, y);
    doc.fillColor(COLORS.ink).text(fmtValue(kpi), startX + 230, y);
    doc.fillColor(COLORS.ink).text(`${kpi.score}`, startX + 330, y);
    doc.fillColor(COLORS[kpi.color] || COLORS.ink).text(kpi.color.toUpperCase(), startX + 420, y);
    y += 20;
  }

  doc.y = y + 10;
  doc.x = startX;

  // Recommendations
  doc.moveDown(0.5);
  doc.fillColor(COLORS.ink).fontSize(14).text("Recommendations");
  doc.moveDown(0.3);
  if (!record.recommendations || record.recommendations.length === 0) {
    doc.fillColor(COLORS.green).fontSize(11).text("All indicators are healthy. Keep up the good performance.");
  } else {
    doc.fontSize(11).fillColor(COLORS.ink);
    record.recommendations.forEach((r) => doc.text(`•  ${r}`, { indent: 4 }).moveDown(0.2));
  }

  doc.moveDown(1.5);
  doc.fillColor(COLORS.muted).fontSize(8)
    .text("Generated by RiskLens — See Risks. Stay Ahead.", { align: "center" });

  doc.end();
}
